### ISSUE TITLE
每日宜忌没有输出

### ISSUE THREAD

**Issue by xinjiayu** [6tail/lunar-go#1]
看你的文档中老黄历的例子里有输出。而在调用程序的时候，没有输出。

**Comment by 6tail** [comment]
@xinjiayu 

我测试有输出的，请问你是怎么调用的？哪一天没有输出？

**Comment by xinjiayu** [comment]
lunar := calendar.NewLunar(2020,8,12,0,0,0)

	glog.Info("宜",lunar.GetDayYi())
	glog.Info("忌",lunar.GetDayJi())

我这是这样调用的

**Comment by 6tail** [comment]
@xinjiayu 不好意思这段时间比较忙，那两个方返回的是*list.List，需要遍历取出，我试了你这个有输出的：

`
        lunar := calendar.NewLunar(2020,8,12,0,0,0)

	for i := lunar.GetDayYi().Front(); i != nil; i = i.Next() {
		fmt.Print(i.Value.(string))
		fmt.Print(" ")
	}
	fmt.Println()
	
	for i := lunar.GetDayJi().Front(); i != nil; i = i.Next() {
		fmt.Print(i.Value.(string))
		fmt.Print(" ")
	}
`
