### ISSUE TITLE
部分大月份计算错误

### ISSUE THREAD

**Issue by liuhedong** [6tail/lunar-go#2]
......
solar = calendar.NewSolar(2012, 12, 18, 12, 0, 0)
_//solar = calendar.NewSolar(2018, 12, 11, 12, 30, 0)_ 
lunar = solar.GetLunar()

// 女运
yun := baZi.GetYun(1)
......

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x10bf30a]
goroutine 1 [running]:
github.com/6tail/lunar-go/calendar.(*JieQi).GetSolar(...)
	JieQi.go:55
github.com/6tail/lunar-go/calendar.(*Yun).computeStart(0xc000162090)
	Yun.go:45 +0xea
github.com/6tail/lunar-go/calendar.NewYun(0xc00000e038, 0x1, 0xc000143c38)
	Yun.go:30 +0x7d
github.com/6tail/lunar-go/calendar.(*EightChar).GetYun(...)
	EightChar.go:296
exit status 2

**Comment by 6tail** [comment]
@liuhedong v1.0.13已修复这个问题，另外这个demo有处笔误已修正，实际GetYun的参数1代表男运，0代表女运。
