### ISSUE TITLE
可否考虑计划增加佛历

### ISSUE THREAD

**Issue by sanrenx** [6tail/lunar-go#4]
首先感谢作者，提供了这么多版本的库，辛苦辛苦！
已经很全面了，希望后续可否考虑增加佛历

JS参考项目:  https://github.com/scalerone/foli/blob/master/foli.js
相关资料网站:
https://www.rili.com.cn/foli/
https://wannianli.tianqi.com/foli/2021.html
http://www.foli.org.cn/  (它的日历控件貌似不准，其他资料倒是挺多):

**Comment by 6tail** [comment]
@sanrenx v1.2.8增加了佛历。

**Comment by 6tail** [comment]
v1.2.8 终于增加了佛历了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "6tail/lunar-go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年1月23日(星期六) 晚上11:09
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[6tail/lunar-go] 可否考虑计划增加佛历 (#4)





 
首先感谢作者，提供了这么多版本的库，辛苦辛苦！
 已经很全面了，希望后续可否考虑增加佛历
