### ISSUE TITLE
每年最后一个月里有闰月时会显示错误

### ISSUE THREAD

**Issue by xuzhiming** [6tail/lunar-go#5]
2033年 12月 22日为闰冬月初一，
实际显示为二〇三三年 腊月 初一。

**Comment by 6tail** [comment]
是的，闰冬月有问题，还要过段时间才能修复。1.2.0及以后的版本都有这个问题。

**Comment by 6tail** [comment]
v1.2.5修复了闰冬月、闰腊月的问题。
